name: tests

variables:
  - group: unittest-samples

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: ["*"]
  containers:
    - container: redis
      image: redis
      ports:
        - 6379:6379
    - container: sftp
      image: linuxserver/openssh-server
      env:
        SUDO_ACCESS: "false"
        PASSWORD_ACCESS: "true"
        USER_PASSWORD: "password"
        USER_NAME: "user"
        LOG_STDOUT: "true"
      ports:
        - 2222:2222
    - container: es7
      image: cccs/elasticsearch:7.17.4
      env:
        ES_JAVA_OPTS: "-Xms256m -Xmx512m"
        DISCOVERY_TYPE: "single-node"
        ELASTIC_PASSWORD: "devpass"
      ports:
        - 9200:9200
    - container: es8
      image: cccs/elasticsearch:8.10.2
      env:
        ES_JAVA_OPTS: "-Xms256m -Xmx512m"
        DISCOVERY_TYPE: "single-node"
        ELASTIC_PASSWORD: "devpass"
      ports:
        - 9200:9200
    - container: minio
      image: cccs/minio
      env:
        MINIO_ROOT_USER: al_storage_key
        MINIO_ROOT_PASSWORD: Ch@ngeTh!sPa33w0rd
      ports:
        - 9000:9000

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_9-es7:
          python.version: "3.9"
          elasticsearch: es7
        python3_9-es8:
          python.version: "3.9"
          elasticsearch: es8
        # python3_10:
        #   python.version: "3.10"

    timeoutInMinutes: 10
    services:
      elasticsearch: $[ variables['elasticsearch'] ]
      sftp: sftp
      redis: redis
      minio: minio

    steps:
      - checkout: self
        fetchDepth: 1
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          sudo mkdir -p /etc/assemblyline/
          sudo mkdir -p /var/cache/assemblyline/
          sudo cp pipelines/config.yml /etc/assemblyline
          sudo chmod a+rw /var/cache/assemblyline/
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev
          sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U pip cython setuptools wheel
          sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e .
          sudo env "PATH=$PATH" python -m pip install --no-cache-dir -r test/requirements.txt
        displayName: Setup environment
      - script: python -m pytest --durations=10 -rsx -vv --ignore=test/test_identify.py
        displayName: Test
  - job: run_identify_test
    container:
      image: cccstemp.azurecr.io/assemblyline-root-build:stable
      endpoint: cccstemp
    timeoutInMinutes: 10
    steps:
      - checkout: self
        fetchDepth: 1
      - checkout: unittest-samples
        fetchDepth: 1
      - script: |
          set -exv
          env "PATH=$PATH" python -m pip install --no-cache-dir -U pip cython setuptools wheel
          env "PATH=$PATH" python -m pip install --no-cache-dir -e assemblyline-base
          env "PATH=$PATH" python -m pip install --no-cache-dir -r assemblyline-base/test/requirements.txt
        displayName: Setup environment
      - script: |
          set -exv
          env "PATH=$PATH" "SAMPLES_LOCATION=$PWD/assemblyline-unittest-samples" python -m pytest --durations=10 -rsx -vv assemblyline-base/test/test_identify.py
        displayName: Test File Identification
