name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: redis
    image: redis
  - container: elasticsearch
    image: cccs/elasticsearch:7.8.0
    env:
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
      DISCOVERY_TYPE: 'single-node'
  - container: minio
    image: cccs/minio
    env:
      MINIO_ACCESS_KEY: al_storage_key
      MINIO_SECRET_KEY: Ch@ngeTh!sPa33w0rd

jobs:
- job: run_test
  strategy:
    matrix:
      python3_7:
        python.version: '3.7'
      python3_8:
        python.version: '3.8'
      python3_9:
        python.version: '3.9'

  timeoutInMinutes: 10
  services:
    elasticsearch: elasticsearch
    redis: redis
    minio: minio
  
  container: 'cccs/assemblyline_dev:test-env-$(python.version)'

  steps:
    - script: |
        sudo cp pipelines/config.yml /etc/assemblyline
        sudo chmod 777 /var/cache/assemblyline/
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U pip cython setuptools
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e .
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -r test/requirements.txt
      displayName: Setup environment
    - script: python -m pytest --durations=10 -rsx -vv --cov-report=xml --cov=assemblyline
      displayName: Test
    - script: python -m codecov
      displayName: Upload Coverage
