name: tests

variables:
  - group: unittest-samples
  # Try to checkout the matching branch, if the command fails, don't care.
  - name: "BRANCH_NAME"
    value: $[coalesce(variables['System.PullRequest.SourceBranch'], variables['System.PullRequest.TargetBranch'], replace(variables['Build.SourceBranch'], 'refs/heads/', ''), 'main')]

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: ["*"]

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_11:
          PYTHON_VERSION: "3.11"
        python3_12:
          PYTHON_VERSION: "3.12"
        python3_13:
          PYTHON_VERSION: "3.13"
        python3_14:
          PYTHON_VERSION: "3.14"

    timeoutInMinutes: 10
    steps:
      - checkout: self
        fetchDepth: 1
      - checkout: unittest-samples
      - script: |
          # Start all services except pytest
          docker compose up -d --wait $(docker compose config --services | grep -v pytest)
        displayName: Setup environment
        workingDirectory: $(System.DefaultWorkingDirectory)/test

      - script: |
          # Start up pytest service from Docker Compose and run the tests
          docker compose run --build pytest pytest --durations=10 -rsx
        displayName: Test
        workingDirectory: $(System.DefaultWorkingDirectory)/test
