filestore:
  cache:
    - file:///var/cache/assemblyline/
  storage:
    - file:///var/cache/assemblyline/
core:
  redis:
    nonpersistent:
      host: localhost
      port: 6379
    persistent:
      host: localhost
      port: 6379
  metrics:
    export_interval: 1
datastore:
  hosts: ["http://elastic:devpass@localhost:9200"]
  archive:
    enabled: true
