filestore:
  cache:
    - file:///var/cache/assemblyline/
  storage:
    - file:///var/cache/assemblyline/
core:
  metrics:
    redis:
      host: redis
      port: 6379
  redis:
    nonpersistent:
      host: redis
      port: 6379
    persistent:
      host: redis
      port: 6379
datastore:
  hosts: ["elasticsearch:9200"]
