FROM sgaroncse/v3_service_base_dev:3.3.1

ENV SERVICE_PATH alsvc_characterize.Characterize

WORKDIR /opt/al/al_services

# Clone Characterize service code
RUN git clone https://bitbucket.org/cse-assemblyline/alsvc_characterize.git