FROM sgaroncse/v3_service_base_dev:3.3.3

ENV SERVICE_PATH alsvc_characterize.Characterize

# Clone Characterize service code
WORKDIR /opt/al/al_services
RUN git clone https://bitbucket.org/cse-assemblyline/alsvc_characterize.git