FROM sgaroncse/v3_service_base_dev:3.3.4

ENV SERVICE_PATH alsvc_pdfid.PDFId

# Clone PDFId service code
WORKDIR /opt/al/al_services
RUN git clone https://bitbucket.org/cse-assemblyline/alsvc_pdfid.git